import type { CostingData, CostingIngredientHistoryEntry } from "../types";

export const visualCostingData: CostingData = {
  sourceFileName: "Visual Costeo Fixture.xlsx",
  importedAt: "2026-07-09T12:00:00.000Z",
  ingredients: [
    {
      id: "cacao-en-polvo",
      nombre: "Cacao en Polvo",
      unidad: "g",
      unidadesPorEnvase: 1000,
      costoEnvase: 305.87,
      costoUnidad: 0.30587,
      proveedor: "Costco",
      marca: "abkkao",
    },
    {
      id: "cacao-en-polvo-turin",
      nombre: "Cacao en Polvo TURIN",
      unidad: "g",
      unidadesPorEnvase: 1,
      costoEnvase: 0.117391,
      costoUnidad: 0.117391,
      proveedor: "HEB",
      marca: "TURIN",
    },
    {
      id: "galletas-oreo",
      nombre: "Galletas oreo",
      unidad: "g",
      unidadesPorEnvase: 432,
      costoEnvase: 59.37,
      costoUnidad: 0.137427,
      proveedor: "Walmart",
      marca: "Oreo",
    },
    {
      id: "azucar-glass",
      nombre: "Azucar glass",
      unidad: "g",
      unidadesPorEnvase: 1000,
      costoEnvase: 52.29,
      costoUnidad: 0.05229,
      proveedor: "HEB",
      marca: "Great Value",
    },
    {
      id: "polvo-matcha",
      nombre: "Polvo de Matcha",
      unidad: "g",
      unidadesPorEnvase: 100,
      costoEnvase: 150,
      costoUnidad: 1.5,
      proveedor: "Costco",
      marca: "Kirkland",
    },
  ],
  recipes: [
    {
      id: "oreo",
      nombre: "OREO",
      producto: "Donas",
      rendimientoReceta: 8,
      rendimientoGlaseado: 8,
      costoReceta: 31.95,
      costoGlaseado: 13.42,
      costoUnitario: 5.67125,
      lines: [
        {
          id: "oreo-receta-cacao",
          section: "receta",
          ingredientId: "cacao-en-polvo",
          ingrediente: "Cacao en Polvo",
          cantidad: 25,
          unidad: "g",
          costoUnidad: 0.30587,
          costoLinea: 7.64675,
        },
        {
          id: "oreo-receta-galletas",
          section: "receta",
          ingredientId: "galletas-oreo",
          ingrediente: "Galletas oreo",
          cantidad: 120,
          unidad: "g",
          costoUnidad: 0.137427,
          costoLinea: 16.49124,
        },
        {
          id: "oreo-glaseado-azucar",
          section: "glaseado",
          ingredientId: "azucar-glass",
          ingrediente: "Azucar glass",
          cantidad: 180,
          unidad: "g",
          costoUnidad: 0.05229,
          costoLinea: 9.4122,
        },
      ],
    },
    {
      id: "chocolate-proteina",
      nombre: "Chocolate Proteina",
      producto: "Donas",
      rendimientoReceta: 12,
      rendimientoGlaseado: 12,
      costoReceta: 317.51,
      costoGlaseado: 47.2,
      costoUnitario: 30.3925,
      lines: [
        {
          id: "proteina-receta-turin",
          section: "receta",
          ingredientId: "cacao-en-polvo-turin",
          ingrediente: "Cacao en Polvo TURIN",
          cantidad: 32.5,
          unidad: "g",
          costoUnidad: 0.117391,
          costoLinea: 3.815207,
        },
        {
          id: "proteina-glaseado-turin",
          section: "glaseado",
          ingredientId: "cacao-en-polvo-turin",
          ingrediente: "Cacao en Polvo TURIN",
          cantidad: 16.666667,
          unidad: "g",
          costoUnidad: 0.117391,
          costoLinea: 1.956517,
        },
      ],
    },
    {
      id: "matcha",
      nombre: "MATCHA",
      producto: "Donas",
      rendimientoReceta: 8,
      rendimientoGlaseado: 8,
      costoReceta: 41.5,
      costoGlaseado: 18,
      costoUnitario: 7.4375,
      lines: [
        {
          id: "matcha-glaseado",
          section: "glaseado",
          ingredientId: "polvo-matcha",
          ingrediente: "Polvo de Matcha",
          cantidad: 12,
          unidad: "g",
          costoUnidad: 1.5,
          costoLinea: 18,
        },
      ],
    },
  ],
  indirectCosts: {
    items: [
      {
        id: "renta-local",
        categoria: "EN COCINA",
        concepto: "Renta Local",
        frecuencia: "Mensual",
        costo: 4000,
        costoMensual: 4000,
      },
      {
        id: "gas-lp",
        categoria: "EN COCINA",
        concepto: "Gas LP",
        frecuencia: "Semanal",
        costo: 405,
        costoMensual: 1620,
      },
    ],
    monthlyTotal: 5620,
    unitsPerMonth: 7800,
    overheadPerUnit: 0.720513,
    averageSellingPrice: 28,
    averageIngredientCost: 6.4,
    expectedGrossProfit: 168480,
    expectedNetProfit: 61820,
  },
};

export const visualCostingHistory: CostingIngredientHistoryEntry[] = [
  {
    id: "hist-matcha-2",
    ingredientId: "polvo-matcha",
    ingredientName: "Polvo de Matcha",
    previousCostoEnvase: 120,
    newCostoEnvase: 150,
    previousUnidadesPorEnvase: 100,
    newUnidadesPorEnvase: 100,
    previousCostoUnidad: 1.2,
    newCostoUnidad: 1.5,
    previousProveedor: "Costco",
    newProveedor: "Costco",
    previousMarca: "Kirkland",
    newMarca: "Kirkland",
    changedFields: ["costoEnvase", "costoUnidad"],
    changedAt: "2026-07-04T14:30:00.000Z",
    changedBy: "admin@plantivoro.test",
    source: "manual",
  },
  {
    id: "hist-oreo-1",
    ingredientId: "galletas-oreo",
    ingredientName: "Galletas oreo",
    previousCostoEnvase: 64.9,
    newCostoEnvase: 59.37,
    previousUnidadesPorEnvase: 432,
    newUnidadesPorEnvase: 432,
    previousCostoUnidad: 0.150231,
    newCostoUnidad: 0.137427,
    previousProveedor: "HEB",
    newProveedor: "Walmart",
    previousMarca: "Oreo",
    newMarca: "Oreo",
    changedFields: ["costoEnvase", "costoUnidad", "proveedor"],
    changedAt: "2026-07-02T09:15:00.000Z",
    changedBy: "admin@plantivoro.test",
    source: "manual",
  },
  {
    id: "hist-turin-1",
    ingredientId: "cacao-en-polvo-turin",
    ingredientName: "Cacao en Polvo TURIN",
    previousCostoEnvase: 0.1,
    newCostoEnvase: 0.117391,
    previousUnidadesPorEnvase: 1,
    newUnidadesPorEnvase: 1,
    previousCostoUnidad: 0.1,
    newCostoUnidad: 0.117391,
    previousProveedor: "",
    newProveedor: "HEB",
    previousMarca: "",
    newMarca: "TURIN",
    changedFields: ["costoEnvase", "costoUnidad", "proveedor", "marca"],
    changedAt: "2026-06-28T18:20:00.000Z",
    changedBy: "admin@plantivoro.test",
    source: "import",
  },
  {
    id: "hist-matcha-1",
    ingredientId: "polvo-matcha",
    ingredientName: "Polvo de Matcha",
    previousCostoEnvase: 105,
    newCostoEnvase: 120,
    previousUnidadesPorEnvase: 100,
    newUnidadesPorEnvase: 100,
    previousCostoUnidad: 1.05,
    newCostoUnidad: 1.2,
    previousProveedor: "Costco",
    newProveedor: "Costco",
    previousMarca: "Kirkland",
    newMarca: "Kirkland",
    changedFields: ["costoEnvase", "costoUnidad"],
    changedAt: "2026-06-10T11:00:00.000Z",
    changedBy: "admin@plantivoro.test",
    source: "manual",
  },
];
